=== Bregi/SvenBregiSokoban/src/test/resources/ch/bfh/ti/projekt1/sokoban/level1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://bfh.ch"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="level" type="bfh:level" xmlns:bfh="http://bfh.ch"/>
    <xs:complexType name="startPosition">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="row"/>
                <xs:attribute type="xs:int" name="column"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="column">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="id" use="optional"/>
                <xs:attribute type="bfh:fieldType" xmlns:bfh="http://bfh.ch" name="type" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="row">
        <xs:sequence>
            <xs:element type="bfh:column" name="column" maxOccurs="unbounded" minOccurs="0"
                        xmlns:bfh="http://bfh.ch"/>
        </xs:sequence>
        <xs:attribute type="xs:int" name="id" use="optional"/>
    </xs:complexType>
    <xs:complexType name="level">
        <xs:sequence>
            <xs:element type="bfh:row" name="row" maxOccurs="unbounded" minOccurs="0" xmlns:bfh="http://bfh.ch"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="bfh:startPosition" name="startPosition" xmlns:bfh="http://bfh.ch"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="fieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="EMPTY"/>
            <xs:enumeration value="PLAYER"/>
            <xs:enumeration value="DIAMOND"/>
            <xs:enumeration value="GOAL"/>
            <xs:enumeration value="COMPLETED"/>
            <xs:enumeration value="WALL"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Bregi/SvenBregiSokoban/src/test/resources/ch/bfh/ti/projekt1/sokoban/level1.xml
<?xml version="1.0"?>
<level xmlns="http://bfh.ch"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://bfh.ch level1.xsd">
    <row id="0">
        <column id="0" type="EMPTY"/>
        <column id="1" type="EMPTY"/>
        <column id="2" type="EMPTY"/>
        <column id="3" type="EMPTY"/>
    </row>
    <row id="1">
        <column id="0" type="WALL"/>
        <column id="1" type="WALL"/>
        <column id="2" type="EMPTY"/>
        <column id="3" type="WALL"/>
    </row>
    <row id="2">
        <column id="0" type="WALL"/>
        <column id="1" type="EMPTY"/>
        <column id="2" type="EMPTY"/>
        <column id="3" type="EMPTY"/>
    </row>
    <row id="3">
        <column id="0" type="WALL"/>
        <column id="1" type="EMPTY"/>
        <column id="2" type="EMPTY"/>
        <column id="3" type="WALL"/>
    </row>
    <row id="4">
        <column id="0" type="WALL"/>
        <column id="1" type="EMPTY"/>
        <column id="2" type="EMPTY"/>
        <column id="3" type="WALL"/>
    </row>
    <name>crazy level 9999</name>
    <startPosition row="2" column="2"/>
</level>
